name: Deploy Static Website to S3

on:
  push:
    branches:
      - main
    paths:
      - 'my-website/**'  # Only trigger when static files change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync static site to S3
        run: aws s3 sync ./terraform-static-site/my-website s3://kensuke-terraform-website --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E10A9W4B15K5XL \
            --paths "/*"